name: Docker Push
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(date +%s)

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags:
            ${{ secrets.DOCKER_USER }}/hmst:${{ steps.vars.outputs.tag }},
            ${{ secrets.DOCKER_USER }}/hmst:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
